---

- name: Install firewalld
  ansible.builtin.package:
    name: firewalld

- name: Enable firewalld service
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: yes

- name: Uninstall iptables-services
  ansible.builtin.package:
    name: "iptables-services"
    state: absent

- name: python-firewall installieren (CentOS 7)
  ansible.builtin.package: name=python-firewall
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == '7'

- name: python-firewall installieren (CentOS 8)
  ansible.builtin.package: name=python3-firewall
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == '8'

- name: Port OpenSSH oeffnen
  ansible.posix.firewalld:
    service: ssh
    permanent: true
    immediate: true
    state: enabled
